// Subject Data
const subjectData = [
  {
    branch: "Computer Science",
    year: 1,
    semester: 1,
    subjects: [
      {
        id: "cs101",
        name: "Mathematics-I",
        code: "BSMA1101",
        credit: "3",
        teacher: "Mrs. Archana Pattnayak",
        syllabus: [
          "Calculus",
          "Matrices",
          "Matrices",
          "Vector spaces",
          "Vector Calculus",
        ],
        resources: [
          { title: "Textbook: Ramana B.V., Higher Engineering Mathematics", link: "#" },
          { title: "Erwin Kreyszig, Advanced Engineering Mathematics", link: "#" },
          { title: "Video Lectures", link: "#" },
        ],
      },
      {
        id: "cs102",
        name: "Physics",
        code: "BSPH1101",
        credit: "3",
        teacher: "Dr. Amit Sinha",
        syllabus: ["Waves", "Optics", "Modern Physics", "Electromagnetism", "Quantum Mechanics"],
        resources: [
          { title: "Textbook: H.C. Verma", link: "#" },
          { title: "Resnick & Halliday", link: "#" },
          { title: "Video Lectures", link: "#" },
        ],
      },
      {
        id: "cs103",
        name: "Programming in C",
        code: "CSPC1101",
        credit: "3",
        teacher: "Prof. R.K. Mishra",
        syllabus: ["Variables", "Loops", "Functions", "Arrays", "Pointers"],
        resources: [
          { title: "Let Us C by Yashavant Kanetkar", link: "#" },
          { title: "C Programming Absolute Beginner’s Guide", link: "#" },
          { title: "NPTEL Lectures", link: "#" },
        ],
      },
      {
        id: "cs104",
        name: "Engineering Mechanics",
        code: "MEEM1101",
        credit: "3",
        teacher: "Dr. Sunita Rani",
        syllabus: ["Statics", "Dynamics", "Friction", "Centroid", "Moment of Inertia"],
        resources: [
          { title: "Engineering Mechanics by Timoshenko", link: "#" },
          { title: "NPTEL Lectures", link: "#" },
          { title: "YouTube Playlist", link: "#" },
        ],
      },
      {
        id: "cs105",
        name: "English Communication",
        code: "HSHU1101",
        credit: "2",
        teacher: "Mrs. Neha Das",
        syllabus: ["Grammar", "Writing Skills", "Public Speaking", "Group Discussion", "Debates"],
        resources: [
          { title: "Raymond Murphy - Grammar in Use", link: "#" },
          { title: "YouTube Practice Sessions", link: "#" },
        ],
      },
      // Labs
      {
        id: "cs106",
        name: "Physics Lab",
        code: "BSPH1102",
        credit: "1",
        teacher: "Dr. Amit Sinha",
        syllabus: ["Optics Lab", "Photoelectric Effect", "Magnetic Field", "Hall Effect", "Diode Experiment"],
        resources: [
          { title: "Lab Manual", link: "#" },
          { title: "Experiment Videos", link: "#" },
        ],
      },
      {
        id: "cs107",
        name: "C Programming Lab",
        code: "CSPL1101",
        credit: "1",
        teacher: "Prof. R.K. Mishra",
        syllabus: ["Basic Programs", "Loops", "Arrays", "Pointers", "File Handling"],
        resources: [
          { title: "GitHub Sample Code", link: "#" },
          { title: "IDE Guide", link: "#" },
        ],
      },
      {
        id: "cs108",
        name: "Engineering Workshop",
        code: "MEWS1101",
        credit: "1",
        teacher: "Mr. Ashok Kumar",
        syllabus: ["Fitting", "Welding", "Carpentry", "Smithy", "Electrical Fitting"],
        resources: [
          { title: "Workshop Manual", link: "#" },
          { title: "Lab Safety Guidelines", link: "#" },
        ],
      },
    ],
  },

  //semester 2
  {
    branch: "Computer Science",
    year: 1,
    semester: 2,
    subjects: [
      {
        id: "cs201",
        name: "Mathematics-II",
        code: "BSMA1201",
        credit: "3",
        teacher: "Dr. A. K. Sahu",
        syllabus: ["Differential Equations", "Laplace Transforms", "Fourier Series", "Z-Transform", "Probability"],
        resources: [
          { title: "Grewal's Higher Engg Maths", link: "#" },
          { title: "NPTEL Lectures", link: "#" },
        ],
      },
      {
        id: "cs202",
        name: "Chemistry",
        code: "BSCY1201",
        credit: "3",
        teacher: "Dr. S. Priya",
        syllabus: ["Thermodynamics", "Electrochemistry", "Polymers", "Corrosion", "Environmental Chemistry"],
        resources: [
          { title: "Engineering Chemistry by Jain & Jain", link: "#" },
          { title: "Online Reference Notes", link: "#" },
        ],
      },
      {
        id: "cs203",
        name: "Data Structures",
        code: "CSDS1201",
        credit: "3",
        teacher: "Mr. P. Nayak",
        syllabus: ["Arrays", "Linked List", "Stacks", "Queues", "Trees", "Graphs"],
        resources: [
          { title: "Data Structures by Horowitz", link: "#" },
          { title: "NPTEL Lectures", link: "#" },
        ],
      },
      {
        id: "cs204",
        name: "Digital Logic Design",
        code: "CSDL1201",
        credit: "3",
        teacher: "Dr. Manoj Kumar",
        syllabus: ["Number Systems", "Logic Gates", "Combinational Circuits", "Sequential Circuits", "Flip-Flops"],
        resources: [
          { title: "Morris Mano", link: "#" },
          { title: "Online Simulations", link: "#" },
        ],
      },
      {
        id: "cs205",
        name: "Environmental Studies",
        code: "EVST1201",
        credit: "2",
        teacher: "Mrs. Meena Mohanty",
        syllabus: ["Ecosystems", "Biodiversity", "Pollution", "Energy Resources", "Sustainability"],
        resources: [
          { title: "E-Book by IGNOU", link: "#" },
          { title: "UNEP Materials", link: "#" },
        ],
      },
      // Labs
      {
        id: "cs206",
        name: "Chemistry Lab",
        code: "BSCY1202",
        credit: "1",
        teacher: "Dr. S. Priya",
        syllabus: ["Volumetric Analysis", "Titration", "Spectrophotometry", "Viscometry", "pH Measurement"],
        resources: [
          { title: "Lab Manual", link: "#" },
        ],
      },
      {
        id: "cs207",
        name: "Data Structures Lab",
        code: "CSDL1202",
        credit: "1",
        teacher: "Mr. P. Nayak",
        syllabus: ["Linked List", "Stacks", "Queues", "Binary Trees", "Graph Traversals"],
        resources: [
          { title: "Code Repo", link: "#" },
        ],
      },
      {
        id: "cs208",
        name: "Digital Design Lab",
        code: "CSDL1203",
        credit: "1",
        teacher: "Dr. Manoj Kumar",
        syllabus: ["Logic Gates", "K-Maps", "Flip-Flops", "Counters", "Multiplexers"],
        resources: [
          { title: "Digital Trainer Kit Manual", link: "#" },
        ],
      },
    ],
  },

  // Semester 3
  {
    branch: "Computer Science",
    year: 2,
    semester: 3,
    subjects: [
      {
        id: "cs301",
        name: "Discrete Mathematics",
        code: "CSDM2101",
        credit: "3",
        teacher: "Dr. B. Tripathy",
        syllabus: ["Sets", "Relations", "Functions", "Boolean Algebra", "Graphs"],
        resources: [{ title: "Kenneth H. Rosen", link: "#" }],
      },
      {
        id: "cs302",
        name: "Computer Organization",
        code: "CSCO2102",
        credit: "3",
        teacher: "Prof. A. Joshi",
        syllabus: ["Number System", "Registers", "ALU", "Memory Hierarchy", "I/O"],
        resources: [{ title: "Computer System Architecture by M. Mano", link: "#" }],
      },
      {
        id: "cs303",
        name: "Object-Oriented Programming",
        code: "CSOO2103",
        credit: "3",
        teacher: "Ms. Anuja Ray",
        syllabus: ["Classes", "Objects", "Inheritance", "Polymorphism", "Templates"],
        resources: [{ title: "C++ Primer by Lippman", link: "#" }],
      },
      {
        id: "cs304",
        name: "Database Management Systems",
        code: "CSDB2104",
        credit: "3",
        teacher: "Dr. A. Choudhury",
        syllabus: ["ER Model", "SQL", "Normalization", "Transactions", "Indexing"],
        resources: [{ title: "Database System Concepts by Korth", link: "#" }],
      },
      {
        id: "cs305",
        name: "Operating Systems",
        code: "CSOS2105",
        credit: "3",
        teacher: "Dr. P. Rao",
        syllabus: ["Processes", "Threads", "Scheduling", "Memory Mgmt", "File Systems"],
        resources: [{ title: "Modern OS by Tanenbaum", link: "#" }],
      },
      // Labs
      {
        id: "cs306",
        name: "OOP Lab",
        code: "CSOO2106",
        credit: "1",
        teacher: "Ms. Anuja Ray",
        syllabus: ["Class Programs", "Inheritance", "File Handling", "Templates"],
        resources: [{ title: "Lab Problems PDF", link: "#" }],
      },
      {
        id: "cs307",
        name: "DBMS Lab",
        code: "CSDB2107",
        credit: "1",
        teacher: "Dr. A. Choudhury",
        syllabus: ["SQL Queries", "Joins", "PL/SQL", "Triggers", "Stored Procedures"],
        resources: [{ title: "Oracle Docs", link: "#" }],
      },
      {
        id: "cs308",
        name: "OS Lab",
        code: "CSOS2108",
        credit: "1",
        teacher: "Dr. P. Rao",
        syllabus: ["Shell Scripting", "Process Scheduling", "Memory Mgmt Simulation"],
        resources: [{ title: "Linux Command Guide", link: "#" }],
      },
    ],
  },
      
  //semester 4
  {
    branch: "Computer Science",
    year: 2,
    semester: 4,
    subjects: [
      {
        id: "cs401",
        name: "Theory of Computation",
        code: "CSTC2201",
        credit: "3",
        teacher: "Dr. R. Mishra",
        syllabus: ["Automata", "Regular Expressions", "CFG", "Turing Machines", "Pumping Lemma"],
        resources: [{ title: "Introduction to Automata Theory - Ullman", link: "#" }],
      },
      {
        id: "cs402",
        name: "Computer Networks",
        code: "CSTN2202",
        credit: "3",
        teacher: "Prof. T. Mahapatra",
        syllabus: ["OSI Model", "TCP/IP", "Routing", "HTTP", "Security"],
        resources: [{ title: "Computer Networks by Tanenbaum", link: "#" }],
      },
      {
        id: "cs403",
        name: "Design and Analysis of Algorithms",
        code: "CSDA2203",
        credit: "3",
        teacher: "Mr. Arindam Roy",
        syllabus: ["Recursion", "Greedy", "DP", "Graphs", "NP-Completeness"],
        resources: [{ title: "CLRS", link: "#" }],
      },
      {
        id: "cs404",
        name: "Software Engineering",
        code: "CSSE2204",
        credit: "3",
        teacher: "Mrs. R. Nayak",
        syllabus: ["SDLC", "Agile", "UML", "Testing", "Project Mgmt"],
        resources: [{ title: "Sommerville SE Book", link: "#" }],
      },
      {
        id: "cs405",
        name: "Professional Ethics",
        code: "HSPE2205",
        credit: "2",
        teacher: "Mr. J. Das",
        syllabus: ["Ethics in Tech", "Privacy", "AI Ethics", "IPR", "Social Responsibility"],
        resources: [{ title: "Online PDFs", link: "#" }],
      },
      // Labs
      {
        id: "cs406",
        name: "CN Lab",
        code: "CSTN2206",
        credit: "1",
        teacher: "Prof. T. Mahapatra",
        syllabus: ["Socket Programming", "Wireshark", "Protocols", "LAN Setup"],
        resources: [{ title: "Lab Manual", link: "#" }],
      },
      {
        id: "cs407",
        name: "DAA Lab",
        code: "CSDA2207",
        credit: "1",
        teacher: "Mr. Arindam Roy",
        syllabus: ["Sorting", "Graphs", "DP Problems", "Greedy", "Backtracking"],
        resources: [{ title: "Code Repo", link: "#" }],
      },
      {
        id: "cs408",
        name: "Software Design Lab",
        code: "CSSE2208",
        credit: "1",
        teacher: "Mrs. R. Nayak",
        syllabus: ["UML", "Use Case Diagrams", "Project Planning"],
        resources: [{ title: "CASE Tools", link: "#" }],
      },
    ],
  },

  //semester 5
  {
    branch: "Computer Science",
    year: 3,
    semester: 5,
    subjects: [
      {
        id: "cs501",
        name: "Artificial Intelligence",
        code: "CSAI3101",
        credit: "3",
        teacher: "Dr. Swati Mishra",
        syllabus: ["Search Algorithms", "Knowledge Rep.", "ML Basics", "NLP", "Agents"],
        resources: [{ title: "AI: A Modern Approach - Russell", link: "#" }],
      },
      {
        id: "cs502",
        name: "Compiler Design",
        code: "CSCD3102",
        credit: "3",
        teacher: "Prof. A. Banerjee",
        syllabus: ["Lexical Analysis", "Parsing", "Syntax Tree", "Code Generation"],
        resources: [{ title: "Compilers by Aho", link: "#" }],
      },
      {
        id: "cs503",
        name: "Web Technologies",
        code: "CSWT3103",
        credit: "3",
        teacher: "Ms. Trisha Nanda",
        syllabus: ["HTML", "CSS", "JavaScript", "Node.js", "MongoDB"],
        resources: [{ title: "MDN Docs", link: "#" }],
      },
      {
        id: "cs504",
        name: "Cloud Computing",
        code: "CSCC3104",
        credit: "3",
        teacher: "Mr. S. Rath",
        syllabus: ["Cloud Models", "Virtualization", "AWS", "Security", "Containers"],
        resources: [{ title: "Cloud Book by Rajkumar Buyya", link: "#" }],
      },
      {
        id: "cs505",
        name: "Management for Engineers",
        code: "HSBE3105",
        credit: "2",
        teacher: "Prof. R. Jena",
        syllabus: ["Leadership", "Marketing", "Finance", "HR", "Startups"],
        resources: [{ title: "Tata McGraw-Hill", link: "#" }],
      },
      // Labs
      {
        id: "cs506",
        name: "AI Lab",
        code: "CSAI3106",
        credit: "1",
        teacher: "Dr. Swati Mishra",
        syllabus: ["A* Algo", "Bayesian Net", "Basic ML", "Classification"],
        resources: [{ title: "Jupyter Notebooks", link: "#" }],
      },
      {
        id: "cs507",
        name: "Compiler Lab",
        code: "CSCD3107",
        credit: "1",
        teacher: "Prof. A. Banerjee",
        syllabus: ["Lex Tool", "YACC", "Parser Design", "Code Opt."],
        resources: [{ title: "Sample Code", link: "#" }],
      },
      {
        id: "cs508",
        name: "Web Tech Lab",
        code: "CSWT3108",
        credit: "1",
        teacher: "Ms. Trisha Nanda",
        syllabus: ["Portfolio", "Form Handling", "APIs", "Mongo Integration"],
        resources: [{ title: "GitHub Projects", link: "#" }],
      },
    ],
  },

  //semester 6
  {
    branch: "Computer Science",
    year: 3,
    semester: 6,
    subjects: [
      {
        id: "cs601",
        name: "Machine Learning",
        code: "CSML3201",
        credit: "3",
        teacher: "Dr. D. Sharma",
        syllabus: ["Regression", "Classification", "SVM", "Clustering", "Model Eval"],
        resources: [{ title: "Hands-On ML by Aurélien Géron", link: "#" }],
      },
      {
        id: "cs602",
        name: "Internet of Things",
        code: "CSIOT3202",
        credit: "3",
        teacher: "Prof. R. Sen",
        syllabus: ["Sensors", "Protocols", "Arduino", "Raspberry Pi", "Cloud"],
        resources: [{ title: "IoT by Vijay Madisetti", link: "#" }],
      },
      {
        id: "cs603",
        name: "Information Security",
        code: "CSIS3203",
        credit: "3",
        teacher: "Ms. A. Rout",
        syllabus: ["Cryptography", "Attacks", "Authentication", "Firewalls", "PKI"],
        resources: [{ title: "William Stallings - Cryptography", link: "#" }],
      },
      {
        id: "cs604",
        name: "Mobile App Development",
        code: "CSMA3204",
        credit: "3",
        teacher: "Mr. A. K. Das",
        syllabus: ["Android Basics", "Layouts", "Intents", "Database", "Firebase"],
        resources: [{ title: "Android Dev Docs", link: "#" }],
      },
      {
        id: "cs605",
        name: "Open Elective-I",
        code: "OECS3205",
        credit: "2",
        teacher: "To Be Announced",
        syllabus: ["Varies based on selection"],
        resources: [{ title: "Provided in-class", link: "#" }],
      },
      // Labs
      {
        id: "cs606",
        name: "ML Lab",
        code: "CSML3206",
        credit: "1",
        teacher: "Dr. D. Sharma",
        syllabus: ["Regression", "Classification", "Clustering"],
        resources: [{ title: "Jupyter Notebooks", link: "#" }],
      },
      {
        id: "cs607",
        name: "IoT Lab",
        code: "CSIOT3207",
        credit: "1",
        teacher: "Prof. R. Sen",
        syllabus: ["Sensor Setup", "Arduino Coding", "IoT Cloud"],
        resources: [{ title: "TinkerCAD Projects", link: "#" }],
      },
      {
        id: "cs608",
        name: "Android Lab",
        code: "CSMA3208",
        credit: "1",
        teacher: "Mr. A. K. Das",
        syllabus: ["UI Design", "Login App", "ListView", "Firebase Auth"],
        resources: [{ title: "GitHub Templates", link: "#" }],
      },
    ],
  },

  //semester 6
  {
    branch: "Computer Science",
    year: 3,
    semester: 6,
    subjects: [
      {
        id: "cs601",
        name: "Machine Learning",
        code: "CSML3201",
        credit: "3",
        teacher: "Dr. D. Sharma",
        syllabus: ["Regression", "Classification", "SVM", "Clustering", "Model Eval"],
        resources: [{ title: "Hands-On ML by Aurélien Géron", link: "#" }],
      },
      {
        id: "cs602",
        name: "Internet of Things",
        code: "CSIOT3202",
        credit: "3",
        teacher: "Prof. R. Sen",
        syllabus: ["Sensors", "Protocols", "Arduino", "Raspberry Pi", "Cloud"],
        resources: [{ title: "IoT by Vijay Madisetti", link: "#" }],
      },
      {
        id: "cs603",
        name: "Information Security",
        code: "CSIS3203",
        credit: "3",
        teacher: "Ms. A. Rout",
        syllabus: ["Cryptography", "Attacks", "Authentication", "Firewalls", "PKI"],
        resources: [{ title: "William Stallings - Cryptography", link: "#" }],
      },
      {
        id: "cs604",
        name: "Mobile App Development",
        code: "CSMA3204",
        credit: "3",
        teacher: "Mr. A. K. Das",
        syllabus: ["Android Basics", "Layouts", "Intents", "Database", "Firebase"],
        resources: [{ title: "Android Dev Docs", link: "#" }],
      },
      {
        id: "cs605",
        name: "Open Elective-I",
        code: "OECS3205",
        credit: "2",
        teacher: "To Be Announced",
        syllabus: ["Varies based on selection"],
        resources: [{ title: "Provided in-class", link: "#" }],
      },
      // Labs
      {
        id: "cs606",
        name: "ML Lab",
        code: "CSML3206",
        credit: "1",
        teacher: "Dr. D. Sharma",
        syllabus: ["Regression", "Classification", "Clustering"],
        resources: [{ title: "Jupyter Notebooks", link: "#" }],
      },
      {
        id: "cs607",
        name: "IoT Lab",
        code: "CSIOT3207",
        credit: "1",
        teacher: "Prof. R. Sen",
        syllabus: ["Sensor Setup", "Arduino Coding", "IoT Cloud"],
        resources: [{ title: "TinkerCAD Projects", link: "#" }],
      },
      {
        id: "cs608",
        name: "Android Lab",
        code: "CSMA3208",
        credit: "1",
        teacher: "Mr. A. K. Das",
        syllabus: ["UI Design", "Login App", "ListView", "Firebase Auth"],
        resources: [{ title: "GitHub Templates", link: "#" }],
      },
    ],
  },

  {
  branch: "Computer Science",
  year: 3,
  semester: 6,
  subjects: [
    {
      id: "cs601",
      name: "Machine Learning",
      code: "CSML3201",
      credit: "3",
      teacher: "Dr. D. Sharma",
      syllabus: ["Regression", "Classification", "SVM", "Clustering", "Model Eval"],
      resources: [{ title: "Hands-On ML by Aurélien Géron", link: "#" }],
    },
    {
      id: "cs602",
      name: "Internet of Things",
      code: "CSIOT3202",
      credit: "3",
      teacher: "Prof. R. Sen",
      syllabus: ["Sensors", "Protocols", "Arduino", "Raspberry Pi", "Cloud"],
      resources: [{ title: "IoT by Vijay Madisetti", link: "#" }],
    },
    {
      id: "cs603",
      name: "Information Security",
      code: "CSIS3203",
      credit: "3",
      teacher: "Ms. A. Rout",
      syllabus: ["Cryptography", "Attacks", "Authentication", "Firewalls", "PKI"],
      resources: [{ title: "William Stallings - Cryptography", link: "#" }],
    },
    {
      id: "cs604",
      name: "Mobile App Development",
      code: "CSMA3204",
      credit: "3",
      teacher: "Mr. A. K. Das",
      syllabus: ["Android Basics", "Layouts", "Intents", "Database", "Firebase"],
      resources: [{ title: "Android Dev Docs", link: "#" }],
    },
    {
      id: "cs605",
      name: "Open Elective-I",
      code: "OECS3205",
      credit: "2",
      teacher: "To Be Announced",
      syllabus: ["Varies based on selection"],
      resources: [{ title: "Provided in-class", link: "#" }],
    },
    // Labs
    {
      id: "cs606",
      name: "ML Lab",
      code: "CSML3206",
      credit: "1",
      teacher: "Dr. D. Sharma",
      syllabus: ["Regression", "Classification", "Clustering"],
      resources: [{ title: "Jupyter Notebooks", link: "#" }],
    },
    {
      id: "cs607",
      name: "IoT Lab",
      code: "CSIOT3207",
      credit: "1",
      teacher: "Prof. R. Sen",
      syllabus: ["Sensor Setup", "Arduino Coding", "IoT Cloud"],
      resources: [{ title: "TinkerCAD Projects", link: "#" }],
    },
    {
      id: "cs608",
      name: "Android Lab",
      code: "CSMA3208",
      credit: "1",
      teacher: "Mr. A. K. Das",
      syllabus: ["UI Design", "Login App", "ListView", "Firebase Auth"],
      resources: [{ title: "GitHub Templates", link: "#" }],
    },
  ],
},

  //semester 7
  {
    branch: "Computer Science",
    year: 4,
    semester: 7,
    subjects: [
      {
        id: "cs701",
        name: "Deep Learning",
        code: "CSDL4101",
        credit: "3",
        teacher: "Dr. I. Pradhan",
        syllabus: ["Neural Nets", "CNN", "RNN", "Backprop", "TensorFlow"],
        resources: [{ title: "Deep Learning by Goodfellow", link: "#" }],
      },
      {
        id: "cs702",
        name: "Big Data Analytics",
        code: "CSBD4102",
        credit: "3",
        teacher: "Prof. A. Nayak",
        syllabus: ["Hadoop", "MapReduce", "Spark", "NoSQL", "Data Lake"],
        resources: [{ title: "Big Data by Seema Acharya", link: "#" }],
      },
      {
        id: "cs703",
        name: "Blockchain Technology",
        code: "CSBC4103",
        credit: "3",
        teacher: "Mr. R. Jha",
        syllabus: ["Hashing", "Consensus", "Ethereum", "Smart Contracts", "Mining"],
        resources: [{ title: "Blockchain by Arshdeep Bahga", link: "#" }],
      },
      {
        id: "cs704",
        name: "Elective-II",
        code: "OECS4104",
        credit: "3",
        teacher: "To Be Announced",
        syllabus: ["Varies based on selection"],
        resources: [{ title: "Provided in-class", link: "#" }],
      },
      {
        id: "cs705",
        name: "Major Project - Phase I",
        code: "CSMP4105",
        credit: "2",
        teacher: "Assigned Guide",
        syllabus: ["Proposal", "Design", "Initial Implementation"],
        resources: [{ title: "Project Template", link: "#" }],
      },
      // Labs
      {
        id: "cs706",
        name: "DL Lab",
        code: "CSDL4106",
        credit: "1",
        teacher: "Dr. I. Pradhan",
        syllabus: ["Image Classification", "RNN Apps", "Keras Models"],
        resources: [{ title: "Colab Notebooks", link: "#" }],
      },
      {
        id: "cs707",
        name: "BDA Lab",
        code: "CSBD4107",
        credit: "1",
        teacher: "Prof. A. Nayak",
        syllabus: ["Hadoop Setup", "Spark Jobs", "Hive Queries"],
        resources: [{ title: "VM + Dataset", link: "#" }],
      },
      {
        id: "cs708",
        name: "Seminar",
        code: "CSSE4108",
        credit: "1",
        teacher: "Panel",
        syllabus: ["Presentation", "Report Writing", "Q&A"],
        resources: [{ title: "IEEE Templates", link: "#" }],
      },
    ],
  },

  //semester 8
  {
    branch: "Computer Science",
    year: 4,
    semester: 8,
    subjects: [
      {
        id: "cs801",
        name: "Major Project - Phase II",
        code: "CSMP4201",
        credit: "6",
        teacher: "Assigned Guide",
        syllabus: ["Implementation", "Testing", "Final Report", "Demo"],
        resources: [{ title: "Final Project Guide", link: "#" }],
      },
      {
        id: "cs802",
        name: "Internship / Industrial Training",
        code: "CSIN4202",
        credit: "6",
        teacher: "Industry Mentor",
        syllabus: ["Internship Work", "Report", "Certificate", "Review"],
        resources: [{ title: "Sample Reports", link: "#" }],
      },
      {
        id: "cs803",
        name: "Elective-III",
        code: "OECS4203",
        credit: "3",
        teacher: "To Be Announced",
        syllabus: ["Varies based on selection"],
        resources: [{ title: "Provided in-class", link: "#" }],
      },
      {
        id: "cs804",
        name: "Comprehensive Viva",
        code: "CSVV4205",
        credit: "2",
        teacher: "Panel",
        syllabus: ["All Core Subjects"],
        resources: [{ title: "Viva QnA Bank", link: "#" }],
      },
      // Labs (dummy, optional)
      {
        id: "cs806",
        name: "Project Review",
        code: "CSMP4208",
        credit: "1",
        teacher: "Internal Guide",
        syllabus: ["Mid-review", "Presentation", "Corrections"],
        resources: [{ title: "Review Rubrics", link: "#" }],
      },
    ],
  }
  
];

// Helper functions
const getBranches = () => {
  return [...new Set(subjectData.map((item) => item.branch))];
};

const getYears = (branch) => {
  const years = subjectData
    .filter((item) => item.branch === branch)
    .map((item) => item.year);
  return [...new Set(years)].sort((a, b) => a - b);
};

const getSemesters = (branch, year) => {
  const semesters = subjectData
    .filter((item) => item.branch === branch && item.year === year)
    .map((item) => item.semester);
  return [...new Set(semesters)].sort((a, b) => a - b);
};

const getSubjects = (branch, year, semester) => {
  const entry = subjectData.find(
    (item) =>
      item.branch === branch && item.year === year && item.semester === semester
  );
  return entry ? entry.subjects : [];
};
